sudo: false
language: python
matrix:
  include:
  - python: 3.6
    env: TOXENV=lint
  - python: 2.7
    env: TOXENV=py27
  - python: 3.4
    env: TOXENV=py34
  - python: 3.5
    env: TOXENV=py35
  - python: 3.6
    env: TOXENV=py36
  - python: 3.7
    env: TOXENV=py37
    dist: xenial
  - python: pypy3.5
    env: TOXENV=pypy3
  allow_failures:
  - python: 2.7
    env: TOXENV=py27

install:
- pip install tox
- pip install codecov
script:
- tox
after_success:
- codecov
